# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='location_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='web.LocationCategory', verbose_name='Location category'),
        ),
    ]
