# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-14 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20180514_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='successful',
            field=models.BooleanField(default=False, verbose_name='Successful'),
        ),
    ]
